version: '3'
services:
  intranetfront:
    container_name: intranetfront
    build: .
    # command: http-server dist
    # command: npm run serve
    command: serve -s dist
    expose:
      - 5000
    env_file:
        vars.env
networks:
    default:
        external:
            name: red

